incomes = ["Salary", "Pocket Money", "Bonus", "Side Job", "Investment", "Other Income"]
expenses = ["Food", "Clothes", "Houseware", "Cosmetic", "Exchange", "Education", "Electric Bill", "Transportation", "Other Expense"]
currency = "VND"
page_title = "Personal Finance Tracker"
page_icon = ":money_with_wings:"  # emojis: https://www.webfx.com/tools/emoji-cheat-sheet/
layout = "wide"
user_income = []
user_expense = []
transactions = []