incomes = ["Salary", "Saving", "Bonus", "Side Job", "Other Income"]
expenses = ["Food", "Housing", "Entertainment", "Investment", "Education", "Utilities", "Transportation", "Other Expense"]
currency = "$"
page_title = "Personal Finance Tracker"
page_icon = ":money_with_wings:"  # emojis: https://www.webfx.com/tools/emoji-cheat-sheet/
layout = "wide"
user_income = []
user_expense = []
transactions = []